#!/usr/bin/env bash
set -e -o pipefail

# Add repo specific metadata here.

PACKAGE_NAME="Plex Media Server"
RELEASE_PACKAGE_NAME="Plex Media Server"
RELEASE_TAG_PACKAGE_NAME="plex"
BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"
UPSTREAM_VERSION_CONFIG_KEY="PLEX_MEDIA_SERVER_VERSION"
PLEX_MEDIA_SERVER_MAINFEST_URL="https://plex.tv/downloads/details/5?build=linux-x86_64&channel=16&distro=debian"
TEST_TYPE="foreground"
TEST_CONTAINER_TYPE="plex-media-server"

current_upstream_version() {
    get_config_arg ${UPSTREAM_VERSION_CONFIG_KEY:?}
}

latest_upstream_version() {
    docker run --rm \
        "$(base_image_name)" \
        sh -c "apt-get -qq update >/dev/null && apt-get -qq -y install libxml2-utils >/dev/null 2>&1 && curl --silent --location '${PLEX_MEDIA_SERVER_MAINFEST_URL:?}' | xmllint --xpath 'string(//MediaContainer/Release/Package/@fileName)' - | sed -E 's@plexmediaserver_([^_]+)_amd64\.deb@\1@g'"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    echo "Updating ${PACKAGE_NAME:?} ${UPSTREAM_VERSION_CONFIG_KEY:?} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_VERSION_CONFIG_KEY:?}" "${latest_ver:?}"
    git add ${ARGS_FILE:?}
}

package_current_release_version() {
    current_upstream_version | sed -E 's/^([0-9.]+)-[0-9a-f]{9}$/\1/g'
}

test_start_container() {
    local container_name="${1:?}"
    # TODO: Add testing logic here.
}
